language: go

sudo: false

addons:
  apt:
    packages:
      - nodejs

before_install:
  - ./install_protobuf
  - export PATH=$PATH:$PWD/protoc
  - npm install -g elm
  - (cd ./protoc-gen-elm/elm_tests/elm && elm package install -y)

install:
  - go get -t -v ./protoc-gen-elm

script: ./run_tests
